name: cochlea-net

channels:
  - conda-forge

dependencies:
  - mobie_utils
  - pip
  - pooch
  - pybdv
  - pytorch
  - python-elf
  - scikit-image
  - seaborn
  - s3fs
  - torch_em >=0.9
  - trimesh
  - z5py >=3
  - zarr >=3
