SYNAPSE_DICT = {
    "M_LR_000226_L": {"synapse_table_name": "synapse_v3_ihc_v4c", "ihc_table_name": "IHC_v4c"},
    "M_LR_000226_R": {"synapse_table_name": "synapse_v3_ihc_v4c", "ihc_table_name": "IHC_v4c"},
    "M_LR_000227_L": {"synapse_table_name": "synapse_v3_ihc_v4c", "ihc_table_name": "IHC_v4c"},
    "M_LR_000227_R": {"synapse_table_name": "synapse_v3_ihc_v4c", "ihc_table_name": "IHC_v4c"},
    "G_EK_000233_L": {"synapse_table_name": "synapse_v3_ihc_v6", "ihc_table_name": "IHC_v6"},
    "G_LR_000233_R": {"synapse_table_name": "synapse_v3_ihc_v6", "ihc_table_name": "IHC_v6"},

    # fHC
    "M_AMD_N139_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "component_list": [1, 4], "protocol": "fHC"},
    "M_AMD_N139_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "component_list": [2, 5, 3], "protocol": "fHC"},
    "M_AMD_N153_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "protocol": "fHC"},
    "M_AMD_N153_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "component_list": [7, 1, 4], "protocol": "fHC"},

    # PELCOfHC1
    "M_AMD_N140_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "component_list": [1, 5], "protocol": "PELCOfHC1"},
    "M_AMD_N140_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "protocol": "PELCOfHC1"},
    "M_AMD_N142_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "protocol": "PELCOfHC1"},
    "M_AMD_N142_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "component_list": [2, 4, 3], "protocol": "PELCOfHC1"},

    # PELCOfHC2
    "M_AMD_000115_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                       "component_list": [7, 6, 4, 1, 5, 3, 9, 8],
                       "protocol": "PELCOfHC2"},
    "M_AMD_N75_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                    "component_list": [1, 3], "protocol": "PELCOfHC2"},
    "M_AMD_N75_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                    "component_list": [1, 5, 12, 4, 2, 13, 7], "protocol": "PELCOfHC2"},
    "M_AMD_N129_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "component_list": [2, 5, 3, 6], "protocol": "PELCOfHC2"},
    "M_AMD_N129_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "component_list": [4, 2, 6], "protocol": "PELCOfHC2"},
    "M_AMD_N162_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "component_list": [7, 3, 1, 5], "protocol": "PELCOfHC2"},
    "M_AMD_N162_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "component_list": [3], "protocol": "PELCOfHC2"},

    # PELCODISCO1
    "M_AMD_N88_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                    "protocol": "PELCODISCO1"},
    "M_AMD_N88_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                    "component_list": [22, 2, 46, 3, 5], "protocol": "PELCODISCO1"},
    "M_AMD_N89_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                    "protocol": "PELCODISCO1"},
    "M_AMD_N89_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                    "component_list": [1, 2], "protocol": "PELCODISCO1"},

    # PELCODISCO2
    "M_AMD_N95_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                    "component_list": [1, 4, 3, 9, 17, 2], "protocol": "PELCODISCO2"},
    "M_AMD_N95_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                    "component_list": [8, 4, 2, 29, 6, 9, 3], "protocol": "PELCODISCO2"},
    "M_AMD_N97_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                    "component_list": [2, 1, 3], "protocol": "PELCODISCO2"},
    "M_AMD_N97_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                    "component_list": [2, 5], "protocol": "PELCODISCO2"},
    "M_AMD_000103_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                       "component_list": [2], "protocol": "PELCODISCO2"},
    "M_AMD_000103_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                       "component_list": [12, 3, 5, 8, 4, 19, 6, 11, 16],
                       "protocol": "PELCODISCO2"},

    # vfDISCO
    "M_LR_000248_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                      "component_list": [1, 2], "protocol": "vfDISCO"},
    "M_LR_000248_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                      "protocol": "vfDISCO"},
    "M_LR_000249_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                      "protocol": "vfDISCO"},
    "M_LR_000249_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                      "protocol": "vfDISCO"},

    # PELCOfDISCO
    "M_AMD_000087_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                       "protocol": "PELCOfDISCO"},
    "M_AMD_000087_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                       "component_list": [5, 2, 4, 3], "protocol": "PELCOfDISCO"},
    "M_AMD_000088_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                       "protocol": "PELCOfDISCO"},
    "M_AMD_000088_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                       "protocol": "PELCOfDISCO"},
    "M_AMD_N163_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "protocol": "PELCOfDISCO"},
    "M_AMD_N163_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                     "protocol": "PELCOfDISCO"},
    "M_AMD_N163_L_v2": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                        "component_list": [4, 6, 2, 1, 3, 5], "protocol": "PELCOfDISCO"},
    "M_AMD_N163_R_v2": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                        "component_list": [1, 2], "protocol": "PELCOfDISCO"},

    # fDISCO
    "M_AMD_000111_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                       "component_list": [3, 5, 1, 2], "protocol": "fDISCO"},
    "M_AMD_000111_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                       "component_list": [1, 3], "protocol": "fDISCO"},
    "M_AMD_000112_L": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                       "component_list": [1, 2], "protocol": "fDISCO"},
    "M_AMD_000112_R": {"synapse_table_name": "synapse_v3_ihc_v4b", "ihc_table_name": "IHC_v4b",
                       "component_list": [1, 2], "protocol": "fDISCO"},
}
